### ISSUE TITLE
This is useless!

### ISSUE THREAD

**Issue by ghost** [serpenscaput/wl9#1] opened 2020-03-14 22:36 UTC
Oh wait, I see you already covered this in point 7. Nevermind then. :octocat:

Where is the dab emojis on github anyway

**Comment by serpenscaput** [comment] 2020-03-14 22:38
> Oh wait, I see you already covered this in point 7. Nevermind then. :octocat:
> 
> Where is the dab emojis on github anyway

The issue is resolved by default.

**Closed as completed by serpenscaput** 2020-03-14 22:38 UTC

**Comment by Chokster37** [comment] 2020-03-14 22:40
:clap:
